// Host-side tests for the parts of the firmware that must agree with the
// gateway or survive power loss. Runs with plain g++, no ESP32 toolchain:
//
//     make firmware-test
//
// What is NOT covered here: anything touching the sensor, Wi-Fi, or real
// flash. Those need hardware.

#include <cassert>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "../src/canonical.h"
#include "../src/ring_buffer.h"

using namespace presence;

static int failures = 0;

static void check(bool cond, const char* name, const std::string& detail = "") {
  if (cond) {
    printf("  PASS  %s\n", name);
  } else {
    printf("  FAIL  %s %s\n", name, detail.c_str());
    failures++;
  }
}

// ---------------------------------------------------------------------
// In-memory storage so buffer logic is testable without LittleFS.
// ---------------------------------------------------------------------
class MemStorage : public Storage {
 public:
  explicit MemStorage(size_t bytes) : buf_(bytes, 0) {}

  bool readAt(size_t offset, uint8_t* dst, size_t len) override {
    if (offset + len > buf_.size()) return false;
    memcpy(dst, buf_.data() + offset, len);
    return true;
  }
  bool writeAt(size_t offset, const uint8_t* src, size_t len) override {
    if (offset + len > buf_.size()) return false;
    if (failNextWrite_) {
      failNextWrite_ = false;
      return false;
    }
    memcpy(buf_.data() + offset, src, len);
    return true;
  }
  size_t capacityBytes() const override { return buf_.size(); }
  bool saveCursors(uint64_t head, uint64_t tail) override {
    head_ = head;
    tail_ = tail;
    return true;
  }
  bool loadCursors(uint64_t* head, uint64_t* tail) override {
    *head = head_;
    *tail = tail_;
    return true;
  }

  // Simulate a power cut partway through a record write.
  void corruptRecord(size_t index) {
    buf_[index * sizeof(PunchRecord) + 4] ^= 0xFF;
  }
  void failNextWrite() { failNextWrite_ = true; }

 private:
  std::vector<uint8_t> buf_;
  uint64_t head_ = 0, tail_ = 0;
  bool failNextWrite_ = false;
};

static PunchRecord makeRecord(uint64_t seq) {
  PunchRecord r{};
  r.seq = seq;
  r.capturedEpochMs = 1755500000000ull + seq;
  r.capturedUptimeMs = seq * 1000;
  r.slotNo = 42;
  r.matchScore = 150;
  r.credentialKind = 0;
  r.timeSource = 0;
  r.directionHint = 0;
  return r;
}

// ---------------------------------------------------------------------

static void testCanonicalString() {
  printf("canonical string\n");

  // Golden vector generated by the Go gateway (see gateway/internal/auth).
  // If this drifts, every device in the field starts returning 401.
  const std::string got = canonicalString(
      "post", "/v1/device/events", 1755500000000LL, "abc123",
      "b7e23ec29af22b0b4e41da31e868d57226121c84d0d1a5d8b1a9a5d0b0c58e1e");

  const std::string want =
      "v1\n"
      "POST\n"
      "/v1/device/events\n"
      "1755500000000\n"
      "abc123\n"
      "b7e23ec29af22b0b4e41da31e868d57226121c84d0d1a5d8b1a9a5d0b0c58e1e";

  check(got == want, "matches the gateway's format", "\n---got---\n" + got);
  check(canonicalString("get", "/x", 1, "n", "d").find("GET") == 3,
        "method is upper-cased");
}

static void testCrcDetectsCorruption() {
  printf("crc32\n");
  const uint8_t a[] = {1, 2, 3, 4, 5};
  uint8_t b[] = {1, 2, 3, 4, 6};
  check(crc32(a, 5) != crc32(b, 5), "differs on a single-bit change");
  check(crc32(a, 5) == crc32(a, 5), "is stable");
  // Known-answer test for CRC-32/IEEE of "123456789".
  const char* s = "123456789";
  check(crc32(reinterpret_cast<const uint8_t*>(s), 9) == 0xCBF43926u,
        "matches the standard check value");
}

static void testAppendAndPeek() {
  printf("buffer append/peek\n");
  MemStorage st(sizeof(PunchRecord) * 8);
  RingBuffer rb(&st);
  assert(rb.begin());

  check(rb.empty(), "starts empty");
  for (uint64_t i = 1; i <= 5; i++) assert(rb.append(makeRecord(i)));
  check(rb.depth() == 5, "depth tracks appends");

  PunchRecord out[10];
  const size_t n = rb.peek(out, 10);
  check(n == 5, "peek returns everything buffered");
  check(out[0].seq == 1 && out[4].seq == 5, "peek returns oldest first");
  check(rb.depth() == 5, "peek does not consume");
}

// The core offline guarantee: nothing is dropped until the SERVER says so.
static void testAckOnlyDropsAcknowledged() {
  printf("ack semantics\n");
  MemStorage st(sizeof(PunchRecord) * 16);
  RingBuffer rb(&st);
  assert(rb.begin());
  for (uint64_t i = 1; i <= 10; i++) assert(rb.append(makeRecord(i)));

  const size_t dropped = rb.ackThrough(4);
  check(dropped == 4, "drops exactly the acknowledged records");
  check(rb.depth() == 6, "keeps the unacknowledged remainder");

  PunchRecord out[16];
  const size_t n = rb.peek(out, 16);
  check(n == 6 && out[0].seq == 5, "resumes from the first unacknowledged seq");

  // A lost response means the device re-sends; the server dedupes.
  const size_t again = rb.ackThrough(4);
  check(again == 0, "re-acking an old seq is a no-op");
}

// A power cut mid-write leaves a torn record. It must be skipped, not fatal,
// and must not stall the drain — the same failure mode as a poison event on
// the server side.
static void testCorruptRecordIsSkipped() {
  printf("power-cut resilience\n");
  MemStorage st(sizeof(PunchRecord) * 8);
  RingBuffer rb(&st);
  assert(rb.begin());
  for (uint64_t i = 1; i <= 4; i++) assert(rb.append(makeRecord(i)));

  st.corruptRecord(1);  // seq 2

  PunchRecord out[8];
  const size_t n = rb.peek(out, 8);
  check(n == 3, "corrupt record is skipped, others survive");
  bool sawTwo = false;
  for (size_t i = 0; i < n; i++) {
    if (out[i].seq == 2) sawTwo = true;
  }
  check(!sawTwo, "the corrupt record is not returned");

  // And it must not block the tail forever.
  rb.ackThrough(4);
  check(rb.empty(), "drain completes past the corrupt record");
}

static void testFailedWriteIsReported() {
  printf("write failure\n");
  MemStorage st(sizeof(PunchRecord) * 4);
  RingBuffer rb(&st);
  assert(rb.begin());

  st.failNextWrite();
  const bool ok = rb.append(makeRecord(1));
  check(!ok, "append reports failure rather than silently succeeding");
  check(rb.depth() == 0, "a failed append does not advance the head");
  // This is why the firmware must beep only AFTER append() returns true:
  // otherwise it would confirm a punch that was never stored.
}

// A very long outage must not brick the reader. Oldest data is sacrificed.
static void testOverflowDropsOldest() {
  printf("overflow\n");
  MemStorage st(sizeof(PunchRecord) * 4);
  RingBuffer rb(&st);
  assert(rb.begin());
  for (uint64_t i = 1; i <= 6; i++) assert(rb.append(makeRecord(i)));

  check(rb.depth() == 4, "depth is capped at capacity");
  PunchRecord out[8];
  const size_t n = rb.peek(out, 8);
  check(n == 4 && out[0].seq == 3, "oldest records are dropped, newest kept");
}

static void testCursorsSurviveReboot() {
  printf("reboot\n");
  MemStorage st(sizeof(PunchRecord) * 8);
  {
    RingBuffer rb(&st);
    assert(rb.begin());
    for (uint64_t i = 1; i <= 3; i++) assert(rb.append(makeRecord(i)));
    rb.ackThrough(1);
  }
  RingBuffer rebooted(&st);
  assert(rebooted.begin());
  check(rebooted.depth() == 2, "head/tail restored from NVS after a restart");
  PunchRecord out[8];
  const size_t n = rebooted.peek(out, 8);
  check(n == 2 && out[0].seq == 2, "resumes at the right sequence");
}

int main() {
  printf("PunchRecord = %zu bytes\n\n", sizeof(PunchRecord));
  testCanonicalString();
  testCrcDetectsCorruption();
  testAppendAndPeek();
  testAckOnlyDropsAcknowledged();
  testCorruptRecordIsSkipped();
  testFailedWriteIsReported();
  testOverflowDropsOldest();
  testCursorsSurviveReboot();

  printf("\n%s\n", failures == 0 ? "all firmware host tests passed" : "FAILURES");
  return failures == 0 ? 0 : 1;
}
